version: '3.8'

services:
  app:
    image: golang:1.19
    container_name: awms-be
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URL=postgres://awms:awms@postgres:5432/awms?sslmode=disable
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src/awms-be
    working_dir: /go/src/awms-be
    command: ["go", "run", "./cmd/awms-be/main.go"]
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: awms
      POSTGRES_USER: awms
      POSTGRES_PASSWORD: awms
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
