name: E2E Test

on:
  push:
    branches:
      # - master
      - 'feature/*'
      - 'bug/*'

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: 'postgres:13.5-alpine'
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres-keycloak:
        image: 'postgres:13.5-alpine'
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      keycloak:
        image: 'ghcr.io/codox/awms-hyperlogic-keycloak:0.0.1'
        env:
          KEYCLOAK_CREATE_ADMIN_USER: true
          KEYCLOAK_ADMIN_USER: test
          KEYCLOAK_ADMIN_PASSWORD: test

          KEYCLOAK_DATABASE_HOST: "127.0.0.1"
          KEYCLOAK_DATABASE_PORT: 5433
          KEYCLOAK_DATABASE_NAME: keycloak
          KEYCLOAK_DATABASE_USER: test
          KEYCLOAK_DATABASE_PASSWORD: test
        ports:
          - 6080:8080
        options: >-
          --health-cmd "curl --retry-connrefused --retry-delay 5 --retry-max-time 60 -f http://localhost:6080/realms/master || exit 1" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        run: npm run test:e2e:ci
