name: Release version

on:
  push:
    tags:
      - 'v*' # Match any tag starting with 'v'
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yml

  e2e-test:
    uses: ./.github/workflows/e2e-test.yml

  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    needs:
      - unit-test
      - e2e-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: rexchoppers
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2


